(() => {
  'use strict';
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const mulberry32=a=>()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};
  function makeStars(n=900,seed=71){const r=mulberry32(seed),arr=[];for(let i=0;i<n;i++){const mag=1.0+Math.pow(r(),.58)*5.5;arr.push({x:r(),y:r(),mag,tw:r()*6.28,warm:r()>.8});}return arr.sort((a,b)=>a.mag-b.mag)}
  const stars=makeStars();
  function fit(canvas){const dpr=Math.min(devicePixelRatio||1,2),rect=canvas.getBoundingClientRect();canvas.width=Math.max(1,rect.width*dpr);canvas.height=Math.max(1,rect.height*dpr);return{ctx:canvas.getContext('2d'),w:rect.width,h:rect.height,dpr}}
  function drawSky(canvas,{limit=6,bg=.03,glow=.12,seedOffset=0}={}){if(!canvas)return;const{ctx,w,h,dpr}=fit(canvas);ctx.setTransform(dpr,0,0,dpr,0,0);const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,`rgb(${6+bg*25},${9+bg*32},${16+bg*45})`);g.addColorStop(1,`rgb(${10+glow*95},${12+glow*70},${18+glow*35})`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);stars.forEach((s,i)=>{if(s.mag>limit)return;const x=((s.x+seedOffset)%1)*w,y=s.y*h,alpha=clamp((limit-s.mag+1)/2.2,.12,1);const radius=clamp((6.8-s.mag)*.48,.35,2.5);ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.fillStyle=s.warm?`rgba(255,228,194,${alpha})`:`rgba(221,237,255,${alpha})`;ctx.fill();if(radius>1.7){ctx.strokeStyle=`rgba(230,240,255,${alpha*.28})`;ctx.beginPath();ctx.moveTo(x-radius*2.5,y);ctx.lineTo(x+radius*2.5,y);ctx.stroke()}})}
  const allCanvases=[];function register(c,opts){if(c){allCanvases.push([c,opts]);drawSky(c,opts)}}
  const hero=document.getElementById('heroSky');register(hero,{limit:6.3,bg:.02,glow:.04});
  const ageCanvas=document.getElementById('ageSky');let currentAge=0;const ageEl=document.getElementById('ageValue'),countEl=document.getElementById('starCount');
  function setAge(age){currentAge=age;const t=age/18,count=Math.round(250+(100-250)*t);ageEl.textContent=Math.round(age);countEl.textContent=count;drawSky(ageCanvas,{limit:6.1-2.25*t,bg:.02+.21*t,glow:.05+.55*t})}
  const steps=[...document.querySelectorAll('.step')];function updateAgeScroll(){let best=steps[0],dist=1e9;steps.forEach(s=>{const d=Math.abs(s.getBoundingClientRect().top-innerHeight*.42);if(d<dist){dist=d;best=s}});setAge(+best.dataset.age)}
  const limitCanvas=document.getElementById('limitSky'),magSlider=document.getElementById('magSlider'),magOutput=document.getElementById('magOutput'),limitCaption=document.getElementById('limitCaption');
  function setLimit(){const v=+magSlider.value;magOutput.value=v.toFixed(1);let cap=v<3?'只剩最亮的恒星与行星':v<4.2?'主要星座仍可辨认':v<5.3?'星座之间的暗星开始出现':'银河可见，暗星丰富';limitCaption.textContent=cap;drawSky(limitCanvas,{limit:v,bg:(6.5-v)*.055,glow:(6.5-v)*.14})}magSlider.addEventListener('input',setLimit);setLimit();
  const locations={
    'times-square':{name:'时代广场',mag:3,glow:.72,milky:'不可见',desc:'最亮的恒星和行星仍容易辨认，大量暗星被背景光淹没。'},
    'central-park':{name:'中央公园',mag:3.6,glow:.55,milky:'不可见',desc:'直接眩光减少、视野更开阔，但公园仍处在城市光穹之中。'},
    'jamaica-bay':{name:'牙买加湾',mag:4.4,glow:.38,milky:'通常不可见',desc:'城市边缘的天空有所改善，较暗恒星重新进入视野。'},
    'pelham-bay':{name:'佩勒姆湾公园',mag:4.8,glow:.30,milky:'极难辨认',desc:'远离核心商业区后，星座周围的结构明显丰富。'},
    'montauk':{name:'更暗参照地',mag:5.7,glow:.12,milky:'条件好时可见',desc:'离开都市光穹后，夜空重新获得层次，银河有机会出现。'}};
  const locCanvas=document.getElementById('locationSky');function setLocation(id){const d=locations[id];document.querySelectorAll('.pin').forEach(b=>b.classList.toggle('active',b.dataset.location===id));document.getElementById('locationName').textContent=d.name;document.getElementById('locationDesc').textContent=d.desc;document.getElementById('locationMag').textContent=`约${d.mag.toFixed(1)}等`;document.getElementById('locationMilky').textContent=d.milky;drawSky(locCanvas,{limit:d.mag,bg:d.glow*.2,glow:d.glow})}document.querySelectorAll('.pin').forEach(b=>b.addEventListener('click',()=>setLocation(b.dataset.location)));setLocation('times-square');
  const multipleData=[['纽约核心区',3.1,.68],['深圳中心区',3.3,.62],['东京核心区',3.5,.56],['普通郊区',4.8,.28],['暗夜保护区',6.2,.05]];const multipleHost=document.getElementById('skyMultiples');multipleData.forEach((d,i)=>{const art=document.createElement('article');art.className='mini-sky';art.innerHTML=`<canvas aria-label="${d[0]}的模拟星空"></canvas><div><h3>${d[0]}</h3><p>可见极限约 ${d[1].toFixed(1)} 等</p></div>`;multipleHost.appendChild(art);drawSky(art.querySelector('canvas'),{limit:d[1],bg:d[2]*.2,glow:d[2],seedOffset:i*.001})});
  const birdSky=document.getElementById('birdSky'),toggle=document.getElementById('lightToggle'),birdCaption=document.getElementById('birdCaption');let lightOn=true;const birds=[];for(let i=0;i<52;i++){const b=document.createElement('i');b.className='bird';b.style.left=`${-10+Math.random()*120}%`;b.style.top=`${10+Math.random()*70}%`;birdSky.appendChild(b);birds.push(b)}function updateBirds(){birdSky.classList.toggle('off',!lightOn);birds.forEach((b,i)=>{const x=lightOn?(50+(Math.random()-.5)*28):(i/51*100);const y=lightOn?(48+(Math.random()-.5)*30):(18+(i%9)*6);b.style.transform=`translate(${x-parseFloat(b.style.left)}vw,${y-parseFloat(b.style.top)}px) rotate(${lightOn?Math.random()*180:8}deg)`});toggle.textContent=lightOn?'关闭高强度灯光':'重新开启灯光';toggle.setAttribute('aria-pressed',String(lightOn));birdCaption.textContent=lightOn?'灯光开启：部分迁徙轨迹向光源聚集并盘旋。':'灯光关闭：轨迹逐渐恢复为更稳定的迁徙方向。'}toggle.addEventListener('click',()=>{lightOn=!lightOn;updateBirds()});updateBirds();
  const labCanvas=document.getElementById('labSky'),temp=document.getElementById('tempSlider'),tempOut=document.getElementById('tempOutput'),score=document.getElementById('glowScore');function updateLab(){const checked=[...document.querySelectorAll('#lightingControls input[type=checkbox]')].filter(x=>x.checked).length;const kelvin=+temp.value;let val=94-checked*13+(kelvin-2200)/180;val=Math.round(clamp(val,18,96));score.textContent=val;tempOut.value=`${kelvin}K`;drawSky(labCanvas,{limit:6.2-(val/100)*2.7,bg:val/420,glow:val/115})}[...document.querySelectorAll('#lightingControls input')].forEach(x=>x.addEventListener('input',updateLab));updateLab();
  const ending=document.getElementById('endingSky');register(ending,{limit:6.15,bg:.015,glow:.04});
  function onScroll(){const doc=document.documentElement,max=doc.scrollHeight-innerHeight;document.getElementById('progressBar').style.width=`${(scrollY/max)*100}%`;if(hero){const r=document.querySelector('.hero').getBoundingClientRect(),p=clamp(-r.top/(r.height-innerHeight),0,1);drawSky(hero,{limit:6.3-p*3.3,bg:.02+p*.2,glow:.04+p*.68})}updateAgeScroll()}
  let ticking=false;addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(()=>{onScroll();ticking=false});ticking=true}},{passive:true});addEventListener('resize',()=>{onScroll();setLimit();setLocation(document.querySelector('.pin.active')?.dataset.location||'times-square');updateLab()});onScroll();
})();
